# Base Settings

BASE_URL = 'https://musicbrainz.org'
BASE_FOLDER = './art/'
SAVE_IMAGES_IN_FORMAT = '.jpg'

# Request Settings
REQUEST_STRIDE = 10
REQUEST_PADDING_IN_SECS = 5
METADATA_REQUEST_TIMEOUT = 2 * 60
PAINTINGS_REQUEST_TIMEOUT = 5 * 60